# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.RemoveField(
            model_name='category',
            name='laptops',
        ),
    ]
