# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0002_auto_20181227_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
